# Setup
title:        Dynamic Stock Industry Classification
tagline:      Use graph-based analysis to re-classify stocks in China A-share and to improve Markowitz portfolio optimization
baseurl:      /dynamic_stock_industry_classification
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sheng Yang
  url:        https://yangshengaa.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown