name: finance-base
channels:
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - numpy=1.19
  - networkx=2.6.3
  - blas=1.0
  - mkl=2021.4.0
  - dsdp=5.8
  - cvxopt=1.2.7
  - glpk=4.65
  - chardet=4.0.0
  - lightgbm=3.3.1
  - ipykernel 
  - notebook

  - python-planarity=0.4.1
  - pip:
    - autopep8==1.5.7
    - gensim==4.1.2
    - h5py==2.10.0
    - pandas==1.3.4
    - pyarrow==4.0.0
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1

    - statsmodels==0.12.2
    - stellargraph==1.2.1
  
    - xgboost==0.90
